apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: test
  namespace: flux-system
spec:
  type: oci
  provider: azure
  url: oci://fluxtests.azurecr.io/charts
  interval: 1m0s
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: test
  namespace: flux-system
spec:
  chart: flux-semver
  version: 1.5.2
  sourceRef:
    kind: HelmRepository
    name: test
  interval: 1m0s
