apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: test
  namespace: flux-system
spec:
  type: oci
  provider: aws
  url: oci://211125720409.dkr.ecr.us-east-1.amazonaws.com
  interval: 1m0s
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: test
  namespace: flux-system
spec:
  chart: flux-semver
  version: 1.5.2
  sourceRef:
    kind: HelmRepository
    name: test
  interval: 1m0s
