apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: image-reflector-controller
  namespace: flux-system
spec:
  provider: gcp
  image: us-docker.pkg.dev/kubernetes-bifrost/flux-tests/image-reflector-controller
  interval: 1m0s
  serviceAccountName: default
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: image-reflector-controller
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: image-reflector-controller
  policy:
    semver:
      range: '>=0.20.0'
