apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: image-reflector-controller
  namespace: flux-system
spec:
  provider: azure
  image: fluxtests.azurecr.io/matheuscscp/fluxcd/image-reflector-controller
  interval: 1m0s
  serviceAccountName: default
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: image-reflector-controller
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: image-reflector-controller
  policy:
    semver:
      range: '>=0.20.0'
