apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: test
  namespace: flux-system
spec:
  provider: gcp
  url: oci://us-docker.pkg.dev/kubernetes-bifrost/flux-tests/oci-artifact
  interval: 1m0s
  serviceAccountName: default
