apiVersion: v1
kind: Secret
metadata:
    name: basic-auth
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:0/9pQw==,iv:ZkhwLVgkiUFAwVWL5Xc86Acbds2cbbmM+FBcEqBkNfo=,tag:UGIV8+ECbrqUDSoalqRISQ==,type:str]
    password: ENC[AES256_GCM,data:DyL3qw==,iv:rxwjltb4rq3eQvUQzNlv3dmgslQrg2IYUYcXiCPW4qc=,tag:B7tyIpxpxxiMMY9mmfdBLg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:211125720409:key/mrk-3179bb7e88bc42ffb1a27d5038ceea25
          created_at: "2025-05-05T19:22:23Z"
          enc: AQICAHhhCeVqKslVE9DQUlDSNyPcCMLZWjxBx2SUro9sZiBw6gFHcXJi8NgrM+EoF8kbQcHLAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqbsX3Ou1RZHWAQ6bAgEQgDtX7t1Qch7VpOZW2bFxBSEVgqyt+aHhiqPGTKa27nzVrhYfJFjcxD3/gO/fr4qaHPBpUFiKZvwYoxP/ew==
          aws_profile: ""
    lastmodified: "2025-05-05T19:22:24Z"
    mac: ENC[AES256_GCM,data:XFuj/4QaXFODUIevKA4zILZWip/6mpg4HQFazbJnYqmpcp/OB9yvLCfp2qhIbGKS0D/2Qw/R+D2U05NTTx0olGi6/3LL4ULf/ZMERZgp3N4g2yDLmwvbtbCa6FK+BMq9xtaqRvRnL2sa6ACU31ISS2nEzDOiILjABiFHTHxKh/Y=,iv:BQvQ+ZwN7+zPNt4dDhaFAI4YjqNazE/UtwNpVwVLHJY=,tag:zM/yA5+wz7PjJYQfQOkLHw==,type:str]
    encrypted_regex: ^stringData$
    version: 3.10.2
