apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  provider: azure
  ref:
    branch: main
  url: https://dev.azure.com/matheuscscp/flux-tests/_git/flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
